$background = 0a0f0f
$onBackground = dce8e7
$surface = 0a0f0f
$surfaceDim = 0a0f0f
$surfaceBright = 242e2e
$surfaceContainerLowest = 000000
$surfaceContainerLow = 0e1515
$surfaceContainer = 131b1b
$surfaceContainerHigh = 192121
$surfaceContainerHighest = 1d2828
$onSurface = dce8e7
$surfaceVariant = 1d2828
$onSurfaceVariant = a2adad
$outline = 6d7778
$outlineVariant = 3f4a4a
$inverseSurface = f6fafa
$inverseOnSurface = 515656
$shadow = 000000
$scrim = 000000
$surfaceTint = 9bd0d1
$primary = 9bd0d1
$primaryDim = 8ec2c4
$onPrimary = 0c4849
$primaryContainer = 255a5c
$onPrimaryContainer = b8edee
$inversePrimary = 336769
$primaryFixed = b7ecee
$primaryFixedDim = a9dedf
$onPrimaryFixed = 0b4748
$onPrimaryFixedVariant = 2f6365
$secondary = b0cccc
$secondaryDim = a3bebe
$onSecondary = 2b4445
$secondaryContainer = 274040
$onSecondaryContainer = a9c4c5
$secondaryFixed = cce8e8
$secondaryFixedDim = bedada
$onSecondaryFixed = 2b4444
$onSecondaryFixedVariant = 476061
$tertiary = c8e6ff
$tertiaryDim = b1d9f8
$onTertiary = 2d5670
$tertiaryContainer = b1d9f8
$onTertiaryContainer = 244d67
$tertiaryFixed = b1d9f8
$tertiaryFixedDim = a3cbea
$onTertiaryFixed = 0a3a53
$onTertiaryFixedVariant = 2e5770
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 4c7f81
$secondaryPaletteKeyColor = 627c7d
$tertiaryPaletteKeyColor = 557c97
$neutralPaletteKeyColor = 737878
$neutralVariantPaletteKeyColor = 6e7979
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 4c7f81
$secondary_paletteKeyColor = 627c7d
$tertiary_paletteKeyColor = 557c97
$neutral_paletteKeyColor = 737878
$neutral_variant_paletteKeyColor = 6e7979
$term0 = 343434
$term1 = 769e00
$term2 = 4de2ca
$term3 = 78fcd9
$term4 = 75b5b8
$term5 = 7aaee9
$term6 = 81d8d0
$term7 = ccdcd5
$term8 = 9aa59f
$term9 = 85b900
$term10 = 2ff7dc
$term11 = cbffee
$term12 = a3c8c6
$term13 = a2c0f7
$term14 = 88ece1
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = dfe0f5
$pink = bae2ff
$mauve = 64cdee
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d2faec
$green = 8bf1e7
$teal = 9eeded
$sky = 93e9ef
$sapphire = 71d6e1
$blue = 5acce0
$lavender = 88d8ed
$klink = 0095a3
$klinkSelection = 0095a4
$kvisited = 008cac
$kvisitedSelection = 008cad
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bdb3
$kpositiveSelection = 00bdb4
$text = dce8e7
$subtext1 = a2adad
$subtext0 = 6d7778
$overlay2 = 5f6869
$overlay1 = 505959
$overlay0 = 434a4b
$surface2 = 353c3d
$surface1 = 282e2e
$surface0 = 191e1f
$base = 0a0f0f
$mantle = 0a0f0f
$crust = 090e0e
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
