# preload = ~/.config/wallpapers/mountain-night.jpg
# preload = ~/.config/wallpapers/arch-girl.png
# preload = ~/.config/wallpapers/arch-chan.png
# wallpaper = DP-6,~/.config/wallpapers/arch-chan.png
# wallpaper = eDP-1,~/.config/wallpapers/arch-chan.png
# #wallpaper = ~/.config/wallpapers/mountain-night.jpg
# # preload=
#
# # Disable bottom message
# splash = false 

wallpaper {
    monitor = eDP-1
    path = ~/.config/wallpapers/arch-chan.png
}
